/* Main.c file generated by New Project wizard
 *
 * Created:   ÖÜËÄ 5ÔÂ 11 2017
 * Processor: AT89C51
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>

sbit K = P2^0;
sbit LED = P2^7;

void delay();
void fun(){
	while(1){
		if(K == 0){
			delay();
			if(K == 0)
			LED = ~LED;
			}
		}
	
	}
void delay(){
	int i = 20000;
	while(i--);
	}
void main(void)
 { 
  fun();
 }