/* Main.c file generated by New Project wizard
 *
 * Created:   ÖÜËÄ 5ÔÂ 11 2017
 * Processor: AT89C51
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>

sbit K = P2^0;
sbit LED = P2^7;

void delay(){
	int i = 1000;
	while(i--);
	}
void main(void)
 { 
  while(1){
	  if(K == 0){
		  LED = 0;
		  
		  }
		  else{
			  LED = 1;
			  }
	  delay();
	  }
 }