/* Main.c file generated by New Project wizard
 *
 * Created:   周三 五月 17 2017
 * Processor: AT89C51
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>
sbit LED = P2^0;

void InitTimer0(void)
{
    TMOD = 0x0d;//门控GATE=1，CT=1计数器功能，工作方式1
    TH0 = 0x0FF;
    TL0 = 0x0FE;
    EA = 1;
    ET0 = 1;
    TR0 = 1;
}

void main(void)
 { 
   InitTimer0();
   while (1)
      ;
 }
void to(void) interrupt 1{
	LED = ~LED;
	TH0 = 0x0FF;
    TL0 = 0x0FE;
}
