/* Main.c file generated by New Project wizard
 *
 * Created:   周二 五月 16 2017
 * Processor: AT89C51
 * Compiler:  Keil for 8051
 */

#include <reg52.h>
#include <stdio.h>
sbit LED = P2^0;
void main(void)
 { 
   EX0 = 1;//打开外部中断0开关
	EA = 1;//总开关
	IT0 = 1;
	while(1);
 }
 
void ljj(void) interrupt 0{
	
	LED = ~LED;
}