/* Main.c file generated by New Project wizard
 *
 * Created:   周四 5月 11 2017
 * Processor: AT89C51
 * Compiler:  Keil for 8051
 */
#include<reg52.h>
#define uchar unsigned char
#define uint unsigned int
void delayMS(unsigned int z);
uchar keyscan(void);
void main(void)
{
    uchar key;
    while(1)
    {
        key=keyscan();
        delayMS(50);
    }
}
void delayMS(unsigned int z)
{
    unsigned i,j;
    for(i=z;i>0;i--)
        for(j=122;j>0;j--);
}
uchar keyscan(void)
{
    uchar scode,scode1,scode2,k;
    P1=0xf0;
    scode1=P1&0xf0;
    if(scode1!=0xf0)
    {
        delayMS(10);
        scode1=P1&0xf0;
        if(scode1!=0xf0)
        {
            scode1=P1^0xf0;          //行号
            P1=0x0f;               
            scode2=P1^0x0f;         //列号
            scode=scode1+scode2;
            switch(scode)
            {
                case 0x11: k=1;break;
                case 0x12: k=2;break;
                case 0x14: k=3;break;
                case 0x18: k=4;break;
                case 0x21: k=5;break;
                case 0x22: k=6;break;
                case 0x24: k=7;break;
                case 0x28: k=8;break;
                case 0x41: k=9;break;
                case 0x42: k=10;break;
                case 0x44: k=11;break;
                case 0x48: k=12;break;
                case 0x81: k=13;break;
                case 0x82: k=14;break;
                case 0x84: k=15;break;
                case 0x88: k=16;break;
                default: k=0;break;
            }
           
        }
    }
    return k;
}