/* Main.c file generated by New Project wizard
 *
 * Created:   周五 五月 12 2017
 * Processor: AT89C51
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>

unsigned char tmp = 0;
sbit LED = P2^0;

void init(){
	TMOD = 0x01;
	TH0 = (65536-50000)/256;//50ms
	TL0 = (65536-50000)%256;
	ET0 = 1;
	EA = 1;
	TR0 = 1;
	}
void main(void)
 { 
   init();
	 while(1);
 }
 
void inte() interrupt 1
 {
	 if(tmp == 10){
		 tmp = 0;
		 LED = ~LED;
		}
		else{
			tmp++; 
		}
	TH0 = (65536-50000)/256;//50ms
	TL0 = (65536-50000)%256;
}