/* Main.c file generated by New Project wizard
 *
 * Created:   周四 5月 11 2017
 * Processor: AT89C51
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>

static unsigned char coded[8] = {0xfe,0xfd,0xfb,0xf7,0xef,0xdf,0xbf,0x7f};
static void fun1();
static void fun2();
static void fun3();

void delay(){
	int i= 10000;
	while(i--);
	}
void main(void){
		fun3();
}

//妏蚚杅郪腔源宒
void fun1(){
	
	int i;
	while(1){
		for(i=0;i<8;i++){
			P2 = coded[i];
			delay();
		}
		for(i=6;i>=0;i--){
			P2 = coded[i];
			delay();
		}
	}
}


//妏蚚硌渀腔源宒
void fun2(){
	int i;
	while(1){
		for(i=0;i<8;i++){
			P2 = *(coded+i);
			delay();
		}
		for(i=7;i>=0;i--){
			P2 = *(coded+i);
			delay();
		}
	}
}


//妏蚚弇痄堍呾
void fun3(){
	unsigned char i;
	unsigned char state = 0xfe;
	while(1){
		state = 0xfe;
		P2 = state;
		delay();
		for(i=0;i<7;i++){
			state = (state<<1)|0x01;
			P2 = state;
			delay();
		}
		for(i=0;i<7;i++){
			state = (state >> 1)|0x80;
			P2 = state;
			delay();
		}
	}
}


