/* Main.c file generated by New Project wizard
 *
 * Created:   周四 五月 11 2017
 * Processor: AT89C51
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>


 
int duan[]={0x3F,0x06,0x5B,0x4F,0x66,0x6D,0x7D,0x07,0x7F,0x6F};
int wei[]={0x01,0x02,0x04,0x08};

void static_pile(unsigned char number){
	if(number <= 9)
	 P2 = ~duan[number];

}

void main(void)
 { 
  static_pile(7);
 }
 