/* Main.c file generated by New Project wizard
 *
 * Created:   周二 五月 16 2017
 * Processor: AT89C51
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>
int duan[]={0x3F,0x06,0x5B,0x4F,0x66,0x6D,0x7D,0x07,0x7F,0x6F};
unsigned char number = 0;
void InitTimer0(void)
{
    TMOD = 0x01;
    TH0 = 0x0FC;
    TL0 = 0x18;
    EA = 1;
    ET0 = 1;
    TR0 = 1;
}

void main(void)
 { 
   InitTimer0();
	P2 = ~duan[number];
 }
 
void ljj() interrupt 1{
	
}