/* Main.c file generated by New Project wizard
 *
 * Created:   周三 五月 17 2017
 * Processor: AT89C51
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>

sbit LE= P2^0;
sbit OE = P2^1;

void main(void)
 { 
	 LE= 0;
	 OE = 0;
	P0 = 0x3f;
	 
 }