/* Main.c file generated by New Project wizard
 *
 * Created:   ÖÜËÄ 5ÔÂ 11 2017
 * Processor: AT89C51
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>

sbit led = P2^0;

void delay(){
	int i = 10000;
	while(i--);
	}
void main(void)
 { 
	led = 0;
	delay();
	 led = 1;
	 delay();
	}
 