/* Main.c file generated by New Project wizard
 *
 * Created:   周四 5月 11 2017
 * Processor: AT89C51
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>
int duan[]={0x3F,0x06,0x5B,0x4F,0x66,0x6D,0x7D,0x07,0x7F,0x6F};
sbit K1 = P1^0;
sbit K2 = P1^7;
char num = 0;

void delay(unsigned int i){
	while(i--);
	}
void main(void)
 { 
	while(1){
		if(K1 == 0){
		 delay(5000);
		if(K1 == 0){
			num ++;
			}
		}
		
	if(K2 == 0){
		 delay(5000);
		if(K2 == 0){
			num --;
			}
		}
	if(num > 99){
		num = 0;
		}
	if(num < 0){
		num = 99;
		}
	//最后数码管显示
	P3 = 0x08;
	P2 = ~duan[num%10];
	delay(1000);
	//倒数第二数码管显示	
	P3 = 0x04;
	P2 = ~duan[num/10];
	delay(1000);
	}
 }