/* Main.c file generated by New Project wizard
 *
 * Created:   周三 5月 17 2017
 * Processor: AT89C51
 * Compiler:  Keil for 8051
 */

#include <reg52.h>
#include <stdio.h>
unsigned char i = 0;
sbit LED = P2^0;
void init(){
	ET0 = 1;
	EA = 1;
	TMOD = 0x09;//工作方式1，GATE=1门控开启
	TR0 = 1;
}

void main()
 { 
   init();
   while (1);
 }


void int0() interrupt 1{
	
	LED = ~LED;
}