/* Main.c file generated by New Project wizard
 *
 * Created:   ÖÜËÄ 5ÔÂ 11 2017
 * Processor: AT89C51
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>
int duan[]={0x3F,0x06,0x5B,0x4F,0x66,0x6D,0x7D,0x07,0x7F,0x6F};
int wei[]={0x01,0x02,0x04,0x08};
void digital_pile_show_number(unsigned char n1,unsigned char n2,unsigned char n3,unsigned char n4);
void delay();
void main(void)
{ 
   while(1){
	   P1 =wei[0];
	   P2 = ~duan[0];
	   delay();
	   P1 =wei[1];
	   P2 = ~duan[0];
	   delay();
	   P1 =wei[2];
	   P2 = ~duan[1];
	   delay();
	   P1 =wei[3];
	   P2 = ~duan[1];
	   delay();
	   }
}
 
 

void delay(){
	int i=100;
	while(i--);
	}
void digital_pile_show_number(unsigned char n1,unsigned char n2,unsigned char n3,unsigned char n4){

	if(n1 <= 9){
		P1 = wei[3];
		P2 = ~duan[n1];
	}else{
		P1 = wei[3];
		P2 = 0x00;
	}
	delay();
	if(n2 <= 9){
		P1 = wei[2];
		P2 = ~duan[n2];
	}else{
		P1 = wei[2];
		P2 = 0x00;
	}
	delay();
	if(n3 <= 9){
		P1 = wei[1];
		P2 = ~duan[n3];
	}else{
		P1 = wei[1];
		P2 = 0x00;
	}
	delay();
	if(n4 <= 9){
		P1 = wei[0];
		P2 = ~duan[n4];
	}else{
		P1 = wei[0];
		P2 = 0x00;
	}
	delay();
}