/* Main.c file generated by New Project wizard
 *
 * Created:   周四 五月 11 2017
 * Processor: AT89C51
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>
sbit RELAY = P2^0;

void delay(){
		int i = 0;
		while(i--);
	}
void main(void)
 { 
   RELAY = ~RELAY;
	delay();
 }